version: '3.8'

services:
  flask-service:
    build:
      context: .
      dockerfile: flask-service/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - flask-service-data:/app/data
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development

  strategy-service:
    build:
      context: ./strategy-service
      dockerfile: Dockerfile
    volumes:
      - ./strategy-service:/app
      - strategy-service-data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - strategy-service 
    command: python scheduler.py 


volumes:
  flask-service-data:
  strategy-service-data:
