version: '3.8'

services:
  flask-service:
    build:
      context: .
      dockerfile: flask-service/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - .:/app  # Local directory mounted to container
      - flask-service-data:/app/data  # Named volume for persistent data
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development

volumes:
  flask-service-data:  # Named volume definition

